
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Ground Rules for AI

The landscape of AI is rapidly changing, and therefore unexpected challenges have occurred from an ethical standpoint. 

We suggest the following guidelines to better ensure that your use and development of AI promotes benefit rather than harm:

1) Recognize that there are some guidelines for ethical use and more will be developed. It is advised that you stay up-to-date on industry-specific guidelines.

2) Consider possible downstream unintended consequences for using AI to create content or for developing new AI tools. 

3) Recognize that AI is not perfect, makes mistakes, is not necessarily better than humans, and is typically best used in the context that it was intended and trained for. It is also only a up-to-date as the data it was trained on. While humans are very good at generalizing knowledge for different contexts, AI systems may struggle with this. Human oversight is needed for important and consequential uses.

4) Realize that AI can often perpetuate bias. AI is created using data generated by humans and often that data can be biased. It is important to use inclusive datasets and seek expert advice.

5) Promote equitable access to AI. Differences in access could further promote disparities. 

6) AI poses security and privacy threats. AI needs to be used and developed carefully with these aspects in mind. Do not use proprietary or private information as prompts for consumer AI tools unless it was specifically designed for private data.

7) AI could also exacerbate issues with the climate crises. Developers should be considerate about their computation needs and not use larger than necessary datasets.

8) Users should be transparent about their use of AI tools in case their is an issue. It makes it easier to trace what happened when things go wrong and it also helps to uplift human contributions to work and art.

9) When developing tools be transparent about what data you used to create your AI systems and be careful to not use work or data from individuals who did not consent to it being used in such ways.

10) Start AI projects slowly to allow time to recognize unexpected behavior in AI systems or unexpected consequences. 

11) Recognize that if AI systems use overly complex models it can be difficult to trace how decisions are made using them.

12) Use multiple AI tools to check if results are consistent and check that results are consistent over time with a given tool.

13) Educate yourself and others. To actually comply with ethical standards, it is vital that users be educated about best practices for use. If you help set standards for an institution or group, it strongly advised that you carefully consider how to educate individuals about those standards of use.

To learn more about how to responsibly use and develop AI, check out our minicourse about avoiding AI harm. 


# VIDEO Knowing the Ground Rules {.unlisted .unnumbered}


<div class = disclaimer>
`r config::get("disclaimer")`
</div>
